production:
  access_key_id: AKIAIQYNTMVDJYJAZOWA
  secret_access_key: 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
  bucket: 3nt
  endpoint:
  secure:
  private:
  expires: 

development:
  access_key_id: AKIAIQYNTMVDJYJAZOWA
  secret_access_key: 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
  bucket: 3nt
  endpoint:
  secure:
  private:
  expires: 
